name: Publish
on:
  push:
    branches:
      - kit # TODO: Change to dev & deploy before merge
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Wrangler publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        id: env
        run: |
          # TODO: Change from kit to dev before merge
          if [[ "${{github.base_ref}}" == "kit" || "${{github.ref}}" == "refs/heads/kit" ]]; then
            echo ::set-output name=env::staging
          fi
          if [[ "${{github.base_ref}}" == "deploy" || "${{github.ref}}" == "refs/heads/deploy" ]]; then
            echo ::set-output name=env::production
          fi
      - name: Build
        run: make build
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          enviroment: ${{ steps.env.outputs.env }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
